# If you want to add a new currency, use this template:
#short_name = "Long name of the coin"

# Which can be expanded into:
#[coins.short_name]
#long_name = "Long name of the coin"
#bitfinex = "The name used for access on the Bitfinex API. Default: [short_name] in CAPSLOCK"
#coinmarketcap = "The name used for access on the CoinMarketCap API. Default: name in kebab-case"

# coinmarketcap can be expanded into:
#[coins.short_name.coinmarketcap]
#id = "The name used for access on the CoinMarketCap API. Default: [short_name.name] in kebab-case"
#conversion_symbol = "The symbol used for access on the CoinMarketCap API. Default: [short_name] in lowercase"


[coins]
usd = "U.S. Dollar"
eur = "Euro"
chf = "Swiss Francs"

eth = "Ethereum"
btc = "Bitcoin"
req = "Request Network"
iot = "Iota"
edo = "eidoo"

[coins.qash]
long_name = "QASH"
bitfinex = "QSH"

[coins.edo]
long_name = "eidoo"
bitfinex = "EDO"
